### ISSUE TITLE
Add `writec3d` function

### ISSUE THREAD

**Issue by halleysfifthinc** [halleysfifthinc/C3D.jl#2]

**Comment by GuillaumeLam** [comment]
Hello @halleysfifthinc! I would be interested in using this module, but would probably need the writec3d function for my use case. How long would it take to implement?

**Comment by halleysfifthinc** [comment]
It depends on what exactly your needs are. Writing a modified/existing c3d file (eg read a file with `readc3d`, modify it or add to it, and then write the changed c3d to disk), should be quicker/easier to implement. Creating a c3d from scratch I expect to be more challenging.

Also, I expect the creating a c3d from scratch would build upon code needed to write a modified c3d.

**Comment by GuillaumeLam** [comment]
I see. My intended use is to use ML to predict c3d files from XSens data. If a certain template/pattern was respected, could this only need modification of a template c3d file and thus circumvent creation of a file?

Not sure if this helps but it would really only be for gait motion ie. only lower half of the body.

**Comment by halleysfifthinc** [comment]
> predict c3d files from XSens data

Predict in what way? Isn't XSens already capable of producing c3d files?

A base/template c3d file would help avoid needing to create a c3d from scratch.

Btw, I'm on the Julialang Slack (same username) if you want to DM to discuss more synchronously.
